CREATE TABLE PROYECTO_VECINAL (
  ID_Proyecto INT IDENTITY(1,1) PRIMARY KEY,
  Nombre NVARCHAR(120) NOT NULL,
  Descripcion NVARCHAR(255),
  FechaInicio DATE,
  FechaFin DATE,
  Bases NVARCHAR(MAX),
  Estado NVARCHAR(30) DEFAULT 'Abierto',
  Fecha_Creacion DATETIME2 DEFAULT SYSDATETIME()
);
CREATE TABLE POSTULACION_PROYECTO (
  ID_Postulacion INT IDENTITY(1,1) PRIMARY KEY,
  ID_Socio INT NOT NULL,
  ID_Proyecto INT NOT NULL,
  Fecha_Postulacion DATETIME2 DEFAULT SYSDATETIME(),
  Estado NVARCHAR(20) DEFAULT 'Pendiente',
  Comentario NVARCHAR(255),
  FOREIGN KEY (ID_Socio) REFERENCES SOCIOS(ID_Socio),
  FOREIGN KEY (ID_Proyecto) REFERENCES PROYECTO_VECINAL(ID_Proyecto)
);