services:
  db:
    image: postgres:15

    restart: always
    env_file:
      - ./unidad-territorial_backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./unidad-territorial_backend

    restart: always
    env_file:
      - ./unidad-territorial_backend/.env
    ports:
      - "4000:4000"
    depends_on:
      - db

  frontend:
    build: ./unidad-territorial
    
    restart: always
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:4000
    depends_on:
      - backend

volumes:
  postgres_data:
